theme="catppuccin_mocha"
[editor]
default-yank-register = "+"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.soft-wrap]
enable = true

[keys.normal]
j = "move_char_left"
k = "move_line_down" 
l = "move_line_up"
";" = "move_char_right"

[keys.select]
j = "extend_char_left"
k = "extend_line_down"
l = "extend_line_up"
";" = "extend_char_right"
