theme="catppuccin_mocha"
[editor]
default-yank-register = "+"

jump-label-alphabet = "asdfjkl;ghqweruioptyzxcvn,m."

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.statusline]
left = ["mode", "spinner", "version-control", "file-name"]
right =  ["diagnostics", "selections", "register", "position-percentage", "position", "file-encoding"]
[editor.soft-wrap]
enable = true

[editor.file-picker]
hidden = false

[keys.normal]
P = [
  "open_below",        # Open a new line below
  "normal_mode",       # Return to normal mode
  "open_below",        # Open a new line below
  "normal_mode",       # Return to normal mode
  "move_line_up",      # Move up to the first empty line
  "paste_after",       # Paste the content
  "move_line_down"     # Move down to position cursor after pasted content
]

j = "goto_word"
l = "symbol_picker"
k = "buffer_picker"
f = "file_picker"

t = "@miW"

"C-u" = ["scroll_up", "scroll_up", "scroll_up", "scroll_up", "scroll_up", "scroll_up", "scroll_up", "scroll_up"]
"C-d" = ["scroll_down", "scroll_down", "scroll_down", "scroll_down", "scroll_down", "scroll_down", "scroll_down", "scroll_down"]

"C-r" = ":rl"
"C-x" = [":w", ":! completeme"]

tab = "goto_last_accessed_file"

backspace = "delete_char_backward"

ret = ["open_below", "normal_mode"]

[keys.select]
j = "extend_to_word"
l = "symbol_picker"
k = "buffer_picker"
f = "file_picker"

t = "@miW"

"C-u" = ["scroll_up", "scroll_up", "scroll_up", "scroll_up", "scroll_up", "scroll_up", "scroll_up", "scroll_up"]
"C-d" = ["scroll_down", "scroll_down", "scroll_down", "scroll_down", "scroll_down", "scroll_down", "scroll_down", "scroll_down"]
