theme="catppuccin_mocha"
[editor]
default-yank-register = "+"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.soft-wrap]
enable = true

[keys.normal]
P = [
  "open_below",        # Open a new line below
  "normal_mode",       # Return to normal mode
  "open_below",        # Open a new line below
  "normal_mode",       # Return to normal mode
  "move_line_up",      # Move up to the first empty line
  "paste_after",       # Paste the content
  "move_line_down"     # Move down to position cursor after pasted content
]

tab = "goto_last_accessed_file"

backspace = "delete_char_backward"

ret = ["open_below", "normal_mode"]
